-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 20:48:03 2023
-- Model: mini video platform model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videos` (
  `id_video` INT NOT NULL,
  `título` VARCHAR(80) NOT NULL,
  `descripción` VARCHAR(200) NULL,
  `tamaño` DECIMAL(5,1) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `duración` TIME NOT NULL,
  `thumbnail` BLOB NOT NULL,
  `estado` ENUM('PUBLICO', 'OCULTO', 'PRIVADO') NULL,
  `reproducciones` INT NOT NULL,
  `likes` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `fecha_publicación` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_video`, `id_usuario`),
  INDEX `fk_videos_usuarios_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_videos_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`etiquetas` (
  `id_etiqueta` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_etiqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`video_etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`video_etiqueta` (
  `etiquetas_id_etiqueta` INT NOT NULL,
  `videos_id_video` INT NOT NULL,
  PRIMARY KEY (`etiquetas_id_etiqueta`, `videos_id_video`),
  INDEX `fk_etiquetas_has_videos_videos1_idx` (`videos_id_video` ASC) VISIBLE,
  INDEX `fk_etiquetas_has_videos_etiquetas1_idx` (`etiquetas_id_etiqueta` ASC) VISIBLE,
  CONSTRAINT `fk_etiquetas_has_videos_etiquetas1`
    FOREIGN KEY (`etiquetas_id_etiqueta`)
    REFERENCES `youtube`.`etiquetas` (`id_etiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiquetas_has_videos_videos1`
    FOREIGN KEY (`videos_id_video`)
    REFERENCES `youtube`.`videos` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`canales` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(200) NULL,
  `fecha_creación` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_canales_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_canales_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`usuario_valoración_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`usuario_valoración_video` (
  `id_usuario` INT NOT NULL,
  `id_video` INT NOT NULL,
  `valoración` ENUM('like', 'dislike') NOT NULL,
  `fecha_valoración` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_video`),
  INDEX `fk_usuarios_has_videos_videos1_idx` (`id_video` ASC) VISIBLE,
  INDEX `fk_usuarios_has_videos_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_videos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_videos_videos1`
    FOREIGN KEY (`id_video`)
    REFERENCES `youtube`.`videos` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`lista_reproducción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`lista_reproducción` (
  `id_lista` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_creación` DATETIME NOT NULL,
  `es_privada` TINYINT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_lista`, `id_usuario`),
  INDEX `fk_lista_reproducción_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_reproducción_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`lista_tiene_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`lista_tiene_videos` (
  `lista_reproducción_id_lista` INT NOT NULL,
  `videos_id_video` INT NOT NULL,
  PRIMARY KEY (`lista_reproducción_id_lista`, `videos_id_video`),
  INDEX `fk_lista_reproducción_has_videos_videos1_idx` (`videos_id_video` ASC) VISIBLE,
  INDEX `fk_lista_reproducción_has_videos_lista_reproducción1_idx` (`lista_reproducción_id_lista` ASC) VISIBLE,
  CONSTRAINT `fk_lista_reproducción_has_videos_lista_reproducción1`
    FOREIGN KEY (`lista_reproducción_id_lista`)
    REFERENCES `youtube`.`lista_reproducción` (`id_lista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_reproducción_has_videos_videos1`
    FOREIGN KEY (`videos_id_video`)
    REFERENCES `youtube`.`videos` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_video` INT NOT NULL,
  `comentario` TEXT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id_comentario`, `id_usuario`, `id_video`),
  INDEX `fk_usuarios_has_videos_videos2_idx` (`id_video` ASC) VISIBLE,
  INDEX `fk_usuarios_has_videos_usuarios2_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_videos_usuarios2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_videos_videos2`
    FOREIGN KEY (`id_video`)
    REFERENCES `youtube`.`videos` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`usuarios_valoración_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`usuarios_valoración_comentarios` (
  `id_usuario` INT NOT NULL,
  `id_comentario` INT NOT NULL,
  `valoración` ENUM('like', 'dislike') NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_comentario`),
  INDEX `fk_usuarios_has_valoracion_comentarios1_idx` (`id_comentario` ASC) VISIBLE,
  INDEX `fk_usuarios_has_valoracion_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_valoracion_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_valoracion_comentarios1`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `youtube`.`comentarios` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `youtube`.`suscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`suscripciones` (
  `usuarios_id_usuario` INT NOT NULL,
  `canales_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `canales_id_usuario`),
  INDEX `fk_usuarios_has_canales_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_suscripciones_canales1_idx` (`canales_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_canales_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `youtube`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suscripciones_canales1`
    FOREIGN KEY (`canales_id_usuario`)
    REFERENCES `youtube`.`canales` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

